Add 'title' to movie scrape + small fixes
nmcassa/letterboxdpy pull request #29
Opened 2024-03-20 08:28 UTC by BeSweets

Adds the ability to get the main title of the movie you scrape.

- fixes intra-number comma splits for alt titles (there's still an issue with alt titles w/ any commas in them, but this is an improvement)
- Returns None for empty genres instead of erroring

2024-03-20 10:07 UTC, fastfingertips approved these changes

2024-03-20 10:10 UTC, fastfingertips requested changes
~if data != None:~

-> if data is not None:
or ->if data:

2024-03-20 19:47 UTC, BeSweets commented
Fixed that, thanks. I think I resubmitted the PR, but I'm still not great at github.

2024-03-21 19:22 UTC, BeSweets commented
Additional changes:
- handles runtimes of 1 minute, >999 minutes, and movies with badges (e.g. Adult).
- mirrors letterboxd handling of special characters in search queries, preventing errors for searches with / in them, as well as more closely aligning results with what you'd get on the website

2024-03-25 15:51 UTC, merged